# to get iter0
# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full

# Data training arguments
dataset_mixer:
  splm/openchat-slimorca_iter3: 1.0
dataset_splits:
- train
preprocessing_num_workers: 12

# Trainer arguments
bf16: true
beta: 0.1
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
hub_model_id: zephyr-7b-spin
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 3
optim: rmsprop
output_dir: outputs
per_device_train_batch_size: 12
per_device_eval_batch_size: 8
push_to_hub: false
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1

# LoRA arguments
#load_in_4bit: false
#use_peft: true
#lora_r: 16
#lora_alpha: 16
#lora_dropout: 0.05
#lora_target_modules:
#- q_proj
#- k_proj
#- v_proj
#- o_proj
#- gate_proj
#- up_proj
#- down_proj